import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Next-js practice",
    template: "%s | Next-Js",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-slate-500 text-7xl text-center p-10 font-bold">
          <h2>Header</h2>
        </header>
        {children}
        <header className="bg-slate-500 text-7xl text-center p-10 font-bold">
          <h2>Footer</h2>
        </header>
      </body>
    </html>
  );
}
